'use server'
import MainContent from '@/components/MainContent'
import { LayoutHeader } from '@/components/Header'
import VideoCarousel from '@/components/VideoCarousel'
import Footer from '@/components/Footer'
import { getDictionary } from './dictionaries'
import { Locale } from '@/i18n-config'
import { translations } from '@/config/translations'
import { InView, useInView } from 'react-intersection-observer'
import { allExampleVideoList } from '@/app/data/openaiExampleVideo'

export default async function Home({ params: { lang } }: { params: { lang: Locale } }) {
    const dictionary = await getDictionary(lang) // en
    const videos = allExampleVideoList;
    const metadata = translations[lang || 'zh-CN']
    return (
        <>
            <header>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <link rel="icon" href="/logo.png"></link>
            </header>
            <main
                className="flex min-h-screen py-auto flex-col items-center justify-center py-12 px-4 bg-home-background bg-cover space-y-6 bg-center">
                <LayoutHeader />
                <div className="top-[10%] left-[15%]">
                    <MainContent dictionary={dictionary} />

                </div>
                {/*<div*/}
                {/*    className="md:w-1/2 md:left-[70%] top-[50%] transform md:-translate-x-1/2 md:-translate-y-1/2">*/}
                <div
                    className="bg-white rounded-2xl border-[14px] border-b-blue-300">
                    <div className="flex flex-col justify-center items-center">
                        <span className="p-10 text-xl md:text-2xl font-bold text-gray-600">Example video generated by Sora</span>
                        <ul>
                            {videos.map((item) => {
                                return (
                                    <li key={item.number}
                                        className="px-[2vh] py-[2vh]  border-y border-y-gray-200 p-2 max-w-2xl">
                                        <VideoCarousel videos={item} />
                                    </li>
                                )
                            })}
                        </ul>
                    </div>
                </div>
                <Footer year={new Date().getFullYear()} companyName="SoraFlows" />
            </main>
        </>
    )
}
